local builtin = require('telescope.builtin')
vim.keymap.set('n', '<leader>ff', function() builtin.find_files() end, {})
vim.keymap.set('n', '<leader>ffh', function() builtin.find_files({hidden = true}) end, {})
vim.keymap.set('n', '<leader>fg', function() builtin.live_grep() end, {})
vim.keymap.set({'n', 'v'}, '<leader>fgs', function() builtin.grep_string() end, {})
vim.keymap.set('n', '<leader>fgc', function() builtin.git_commits() end, {})
vim.keymap.set('n', '<leader>fb', function() builtin.buffers() end, {})
vim.keymap.set('n', '<leader>fh', function() builtin.help_tags() end, {})
vim.keymap.set('n', '<leader>fq', function() builtin.quickfix() end, {})
vim.keymap.set('n', '<leader>fqq', function() builtin.quickfixhistory() end, {})
vim.keymap.set('n', '<leader>fj', function() builtin.jumplist() end, {})
vim.keymap.set('n', '<leader>fm', function() builtin.marks() end, {})
vim.keymap.set('n', '<leader>fr', function() builtin.lsp_references() end, {})
vim.keymap.set('n', '<leader>frr', function() builtin.registers() end, {})
vim.keymap.set('n', '<leader>fo', function() builtin.lsp_outgoing_calls() end, {})
vim.keymap.set('n', '<leader>fd', function() builtin.lsp_definitions() end, {})
vim.keymap.set('n', '<leader>fs', function() builtin.lsp_document_symbols() end, {})
vim.keymap.set('n', '<leader>fws', function() builtin.lsp_dynamic_workspace_symbols() end, {})
