//! HTTP client for Battle.net's local Agent service.
//!
//! ## Background
//!
//! Battle.net.exe spawns an Agent process at login that listens on
//! `http://127.0.0.1:<port>` (port read from `Agent.dat` in the prefix).
//! Agent provides REST endpoints for game-session management,
//! installation/update orchestration, and "what's running" queries.
//!
//! Authentication is a single header: `Authorization: <numeric-token>`
//! (no `Bearer` prefix). The token is generated by Agent at startup and
//! embedded in its log file. Battle.net.exe reads the log to learn the
//! token.
//!
//! ## Why we need this
//!
//! For the "warm launch" of Overwatch, we replicate the HTTP requests
//! Battle.net makes when the user clicks Play:
//!
//! 1. `POST /gamesession` registers the spawned game's Wine PID with Agent.
//! 2. `POST /priorities` marks the game as foreground.
//!
//! Both are required to match Battle.net's exact wire format
//! (Content-Type: text/plain, custom `pid:` header, etc.) so Agent
//! treats our requests as authentic.

use anyhow::{Context, Result};
use serde::Deserialize;
use std::collections::HashMap;
use std::path::{Path, PathBuf};
use std::time::Duration;

const HTTP_TIMEOUT: Duration = Duration::from_secs(5);

/// Live connection details for talking to Battle.net Agent.
pub struct AgentClient {
    pub port: u16,
    pub token: String,
}

impl AgentClient {
    /// Probe the Wine prefix for a running Agent. Returns `Ok(None)` if
    /// Agent is not running or its credentials can't be located.
    pub fn discover(prefix: &Path) -> Option<Self> {
        let port = read_agent_port(prefix)?;
        let token = read_agent_token(prefix)?;

        // Verify the credentials work before returning. If Agent is dead
        // or the token is stale, we want the caller to see None and fall
        // back to the safe path.
        let client = Self { port, token };
        if client.healthcheck().is_err() {
            return None;
        }
        Some(client)
    }

    /// Issue a base HTTP request with the canonical Battle.net headers.
    /// `caller_pid` is the Wine PID of the calling Battle.net process —
    /// included so Agent treats the request as authentic. We pass the
    /// Battle.net.exe Wine PID we discover via [`battle_net_pid`].
    fn request(
        &self,
        method: &str,
        path: &str,
        body: Option<&str>,
        caller_pid: Option<u32>,
    ) -> Result<ureq::Response> {
        let url = format!("http://127.0.0.1:{}{}", self.port, path);
        let agent = ureq::AgentBuilder::new()
            .timeout(HTTP_TIMEOUT)
            // Match Battle.net's User-Agent exactly. Agent likely doesn't
            // verify this, but matching reduces our fingerprint footprint.
            .user_agent("phoenix-agent/1.0")
            .build();

        let mut req = match method {
            "GET" => agent.get(&url),
            "POST" => agent.post(&url),
            other => anyhow::bail!("Unsupported method: {}", other),
        };

        req = req.set("Authorization", &self.token).set("Accept", "*/*");
        if let Some(pid) = caller_pid {
            req = req.set("pid", &pid.to_string());
        }

        let response = if let Some(body) = body {
            // Battle.net uses `text/plain` for these JSON payloads. Agent
            // accepts JSON regardless, but matching the wire format
            // exactly keeps us indistinguishable from real Battle.net.
            req.set("Content-Type", "text/plain")
                .send_string(body)
                .with_context(|| format!("{} {} failed", method, path))?
        } else {
            req.call()
                .with_context(|| format!("{} {} failed", method, path))?
        };

        Ok(response)
    }

    fn healthcheck(&self) -> Result<()> {
        let resp = self.request("GET", "/agent", None, None)?;
        if resp.status() != 200 {
            anyhow::bail!("Agent /agent returned {}", resp.status());
        }
        Ok(())
    }

    /// GET /gamesession parsed into the map Agent returns.
    /// Format: `{ "<uid>": { "<index>": GameSession, ... }, ... }`
    pub fn list_sessions(&self) -> Result<HashMap<String, HashMap<String, GameSession>>> {
        let resp = self.request("GET", "/gamesession", None, None)?;
        let parsed: HashMap<String, HashMap<String, GameSession>> =
            resp.into_json().context("parsing /gamesession response")?;
        Ok(parsed)
    }

    /// Look up a representative Wine PID for any "battle.net" session.
    /// We use this as the `pid:` header value when registering OW so
    /// Agent sees the request as coming from a known Battle.net process.
    pub fn battle_net_pid(&self) -> Result<Option<u32>> {
        let sessions = self.list_sessions()?;
        let bnet = match sessions.get("battle.net") {
            Some(m) => m,
            None => return Ok(None),
        };
        // Pick the lowest pid (typically Battle.net.exe's main process,
        // not a CEF helper). Battle.net's main process is generally the
        // one with the smallest Wine PID.
        let min_pid = bnet
            .values()
            .filter(|s| s.pid > 0)
            .map(|s| s.pid as u32)
            .min();
        Ok(min_pid)
    }

    /// Look up Wine PIDs currently registered for a given UID (e.g.
    /// "prometheus" for Overwatch). Used to detect when our spawn shows
    /// up in Agent's tracking.
    pub fn pids_for_uid(&self, uid: &str) -> Result<Vec<u32>> {
        let sessions = self.list_sessions()?;
        Ok(sessions
            .get(uid)
            .map(|m| m.values().map(|s| s.pid as u32).filter(|&p| p > 0).collect())
            .unwrap_or_default())
    }

    /// POST /gamesession to register a spawned game with Agent.
    /// Body matches what Battle.net sends:
    ///   {"binary_type":"game","pid":<wine_pid>,"uid":"<uid>"}
    pub fn register_game(
        &self,
        uid: &str,
        wine_pid: u32,
        caller_pid: u32,
    ) -> Result<()> {
        let body = format!(
            r#"{{"binary_type":"game","pid":{},"uid":"{}"}}"#,
            wine_pid, uid
        );
        let resp = self.request("POST", "/gamesession", Some(&body), Some(caller_pid))?;
        let status = resp.status();
        if status < 200 || status >= 300 {
            anyhow::bail!("/gamesession returned {}", status);
        }
        Ok(())
    }

    /// POST /priorities with the foreground game UID.
    /// Body: {"priorities":["<uid>"]}
    /// Battle.net sends this right after spawning to mark which game
    /// should get bandwidth priority for updates.
    pub fn set_priorities(&self, uids: &[&str], caller_pid: u32) -> Result<()> {
        let json_array = uids
            .iter()
            .map(|u| format!(r#""{}""#, u))
            .collect::<Vec<_>>()
            .join(",");
        let body = format!(r#"{{"priorities":[{}]}}"#, json_array);
        let resp = self.request("POST", "/priorities", Some(&body), Some(caller_pid))?;
        let status = resp.status();
        if status < 200 || status >= 300 {
            anyhow::bail!("/priorities returned {}", status);
        }
        Ok(())
    }
}

/// One row from Agent's GET /gamesession response.
///
/// `binary_type`, `pid_path`, `request_id` are captured for completeness
/// (and future debug surfacing) but currently unused. We marked them
/// dead-code-suppressed rather than dropped so we don't have to redeserialize
/// if/when we need them.
#[derive(Debug, Clone, Deserialize)]
#[allow(dead_code)]
pub struct GameSession {
    #[serde(default)]
    pub binary_type: String,
    /// Wine PID of the game process. Can be `-1` if Agent is tracking a
    /// session whose process has already exited.
    #[serde(default)]
    pub pid: i64,
    #[serde(default)]
    pub pid_path: String,
    #[serde(default)]
    pub request_id: i64,
}

fn agent_dat_path(prefix: &Path) -> PathBuf {
    prefix.join("drive_c/ProgramData/Battle.net/Agent/Agent.dat")
}

/// Read the port Agent is listening on. Agent writes a single ASCII
/// integer (no newline) to `Agent.dat` at startup.
fn read_agent_port(prefix: &Path) -> Option<u16> {
    let content = std::fs::read_to_string(agent_dat_path(prefix)).ok()?;
    content.trim().parse::<u16>().ok()
}

/// Find the most recent Agent log directory. Agent stores logs at
/// `Agent/Agent.<version>/Logs/Agent-<timestamp>.log`. The version
/// directory name uses a build number; we pick whichever directory
/// exists (typically only one for a given install).
fn agent_logs_dir(prefix: &Path) -> Option<PathBuf> {
    let agent_root = prefix.join("drive_c/ProgramData/Battle.net/Agent");
    let entries = std::fs::read_dir(&agent_root).ok()?;
    for e in entries.flatten() {
        if e.file_type().map(|t| t.is_dir()).unwrap_or(false) {
            let name = e.file_name();
            if name.to_string_lossy().starts_with("Agent.") {
                let logs = e.path().join("Logs");
                if logs.is_dir() {
                    return Some(logs);
                }
            }
        }
    }
    None
}

/// Find the most recently modified `Agent-*.log` file.
fn most_recent_agent_log(prefix: &Path) -> Option<PathBuf> {
    let logs_dir = agent_logs_dir(prefix)?;
    let entries = std::fs::read_dir(&logs_dir).ok()?;
    let mut newest: Option<(std::time::SystemTime, PathBuf)> = None;
    for e in entries.flatten() {
        let path = e.path();
        let name = path.file_name()?.to_string_lossy().to_string();
        if !name.starts_with("Agent-") || !name.ends_with(".log") {
            continue;
        }
        let mtime = e.metadata().ok()?.modified().ok()?;
        match &newest {
            Some((old, _)) if old >= &mtime => {}
            _ => newest = Some((mtime, path)),
        }
    }
    newest.map(|(_, p)| p)
}

/// Read the Agent auth token from the most recent log file. The token
/// appears in JSON-formatted response bodies in the log:
/// ```text
///   "authorization": "9487550018965591789",
/// ```
fn read_agent_token(prefix: &Path) -> Option<String> {
    let log = most_recent_agent_log(prefix)?;
    let content = std::fs::read_to_string(log).ok()?;
    // Find the first occurrence of "authorization": "<digits>"
    for line in content.lines() {
        if let Some(idx) = line.find(r#""authorization""#) {
            let rest = &line[idx + r#""authorization""#.len()..];
            if let Some(start) = rest.find('"') {
                if let Some(end_offset) = rest[start + 1..].find('"') {
                    let token = &rest[start + 1..start + 1 + end_offset];
                    if !token.is_empty() && token.chars().all(|c| c.is_ascii_digit()) {
                        return Some(token.to_string());
                    }
                }
            }
        }
    }
    None
}
